# =============================================================
# Bitcoin Core Configuration — OmniNode
# =============================================================

# Network — testnet
testnet=1

# RPC Settings
server=1
rpcuser=omninode_btc
rpcpassword=OmniNode@2025!
rpcallowip=127.0.0.1
rpcallowip=172.16.0.0/12
rpcbind=0.0.0.0
rpcport=8332

# P2P
listen=1
port=8333

# Performance
dbcache=512
maxmempool=300
maxconnections=25

# Pruning — keeps disk usage manageable for demo
prune=550

# Logging
debug=0
printtoconsole=1

# ZMQ — for real-time transaction streaming (Project 3)
zmqpubrawblock=tcp://0.0.0.0:28332
zmqpubrawtx=tcp://0.0.0.0:28333
